In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.14.0


In [3]:
arr=np.arange(10)
print (arr)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
pwd


'C:\\users\\ahlswede\\Documents\\Martina\\Python'

In [6]:
cd \users\ahlswede\Documents\Martina\Python


C:\users\ahlswede\Documents\Martina\Python


In [8]:
a=np.arange(15).reshape(3,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
a.shape

(3, 5)

In [12]:
a.ndim

2

In [13]:
a.dtype.name

'int32'

In [14]:
a.itemsize

4

In [18]:
a=np.array([2,3,4])
a

array([2, 3, 4])

In [19]:
a.dtype

dtype('int32')

In [34]:
pwd

'C:\\users\\ahlswede\\Documents\\Martina\\Python'

In [35]:
import pandas as pd

In [69]:
df = pd.read_csv('countries.csv')
df

Name     People     Area   BIP Currency
0   Germany   82521653   357385  3466      EUR
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL

In [39]:
len(df)

5

In [41]:
df.columns

Index(['Name', 'People', 'Area', 'BIP', 'Currency'], dtype='object')

In [42]:
df4 = df[df['Area'].gt(1000000)]
df4

Name     People     Area   BIP Currency
2    Canada   36503097  9984670  1529      CAD
4  Brazilia  208360000  8515770  1798     REAL

In [70]:
df

Name     People     Area   BIP Currency
0   Germany   82521653   357385  3466      EUR
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL

In [66]:
df.index[0]

0

In [72]:
df["Area"].gt(1000000)

0    False
1    False
2     True
3    False
4     True
Name: Area, dtype: bool

In [78]:
if ( df["Area"].gt(1000000) ): df["Area"]="BIG"

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [110]:
df["Area"].replace(df["Area"].lt(1000000),"SMALL") # is nix
df

Name     People     Area   BIP Currency
0   Germany   82521653   357385  3466      EUR
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL

In [92]:
average = df["People"].sum()/len(df)
average

102786293.6

In [95]:
average =df["People"].median()
average

82521653.0

In [97]:
average= df["People"].mean()
average

102786293.6

In [253]:
df = pd.read_csv("https://raw.githubusercontent.com/edlich/eternalrepo/master/DS-WAHLFACH/countries.csv")
df

Name     People     Area   BIP Currency
0   Germany   82521653   357385  3466      EUR
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL

In [222]:
df["Area"].where(df["Area"].gt(1000000), "BIG")

0        BIG
1        BIG
2    9984670
3        BIG
4    8515770
Name: Area, dtype: object

In [223]:
df["Area"].where(df["Area"].le(1000000), "SMALL")

0    357385
1    377835
2     SMALL
3    301338
4     SMALL
Name: Area, dtype: object

In [251]:
df6=df
df6["Area"] = df["Area"].where(df["Area"].le(1000000), "SMALL")
df6

Name     People    Area   BIP Currency
0   Germany   82521653  357385  3466      EUR
1     Japan  126045000  377835  4938      YEN
2    Canada   36503097   SMALL  1529      CAD
3     Italy   60501718  301338  1850      EUR
4  Brazilia  208360000   SMALL  1798     REAL

In [247]:
print(df)

       Name     People     Area   BIP Currency
0   Germany   82521653   357385  3466      EUR
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL


In [248]:
df7=df
df7["Area"] = df["Area"].where(df["Area"].gt(1000000), "BIG", "SMALL")
print (df7)

ValueError: For argument "inplace" expected type bool, received type str.

In [255]:
df7["Area"] = np.where(df["Area"].gt(1000000), "BIG", "SMALL")

In [256]:
df7

Name     People   Area   BIP Currency
0   Germany   82521653  SMALL  3466      EUR
1     Japan  126045000  SMALL  4938      YEN
2    Canada   36503097    BIG  1529      CAD
3     Italy   60501718  SMALL  1850      EUR
4  Brazilia  208360000    BIG  1798     REAL